# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 08:06
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160602_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
