# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160609_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
