# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160609_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_fr',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fr',
            field=models.CharField(max_length=25, null=True, verbose_name='Article'),
        ),
    ]
