# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160610_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_fr',
            field=models.CharField(max_length=25, null=True, verbose_name='Titre'),
        ),
    ]
