# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_auto_20160604_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='stages',
        ),
        migrations.AddField(
            model_name='tripstage',
            name='trips',
            field=models.ManyToManyField(to='map.Trip', verbose_name='Trips'),
        ),
    ]
