# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 08:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_trip_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstage',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
