# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 08:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_auto_20160604_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(5.0 44.5)', srid=4326),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(5.0 44.5)', srid=4326),
        ),
    ]
