# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_auto_20160604_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='picture_tag',
            field=models.ImageField(blank=True, null=True, upload_to='picture/%Y/%m', verbose_name='Picture tag'),
        ),
    ]
