# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_trip_picture_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStageTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Trip')),
                ('tripstage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.TripStage')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_stages',
            field=models.ManyToManyField(through='map.TripStageTrip', to='map.TripStage', verbose_name='Trip Stages'),
        ),
    ]
