# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_auto_20160604_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_stages',
        ),
    ]
