# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_auto_20160604_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstage',
            name='picture_tag',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/picture/%Y/%m', verbose_name='Picture tag'),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='story',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
