# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 08:41
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0030_auto_20160606_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
