# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0033_auto_20160606_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='nbr_of_days',
            field=models.IntegerField(blank=True, default=1, verbose_name='Nbr of days'),
            preserve_default=False,
        ),
    ]
