# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0034_trip_nbr_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstage',
            name='massif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Massif', verbose_name='Massif'),
        ),
    ]
