# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 22:01
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0037_auto_20160606_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='picture_tag',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Picture'),
        ),
    ]
