# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0039_auto_20160607_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='tripstage',
            name='stage_slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
