# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0040_auto_20160609_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='stage_slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
