# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0041_auto_20160609_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_year',
            field=models.IntegerField(blank=True, default=2016, verbose_name='Année'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='nbr_of_days',
            field=models.IntegerField(blank=True, verbose_name='Nbr de jours'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='picture_tag',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Photo principale'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(max_length=50, verbose_name="Nom de l'aventure"),
        ),
    ]
