# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 10:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0042_auto_20160610_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['start_date'], 'verbose_name': 'Aventure', 'verbose_name_plural': 'Aventures'},
        ),
        migrations.AlterModelOptions(
            name='tripstage',
            options={'ordering': ['date'], 'verbose_name': 'Etape', 'verbose_name_plural': 'Etapes'},
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='added_by',
            field=models.CharField(default='Admin', max_length=50, verbose_name='Ajouté par'),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Durée (h)'),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='email_validation',
            field=models.BooleanField(verbose_name="Validation de l'email"),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='picture_tag',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Photo principale'),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='stage_name',
            field=models.CharField(max_length=50, verbose_name="Nom de l'étape"),
        ),
        migrations.AlterField(
            model_name='tripstage',
            name='trips',
            field=models.ManyToManyField(to='map.Trip', verbose_name='Aventures liées'),
        ),
    ]
