# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0045_tripstage_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='massif',
            name='massif_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Massif'),
        ),
        migrations.AddField(
            model_name='massif',
            name='massif_fr',
            field=models.CharField(max_length=25, null=True, verbose_name='Massif'),
        ),
        migrations.AddField(
            model_name='trip',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name="Nom de l'aventure"),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name="Nom de l'aventure"),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_slug_fr',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='tripstage',
            name='stage_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name="Nom de l'étape"),
        ),
        migrations.AddField(
            model_name='tripstage',
            name='stage_name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name="Nom de l'étape"),
        ),
        migrations.AddField(
            model_name='tripstage',
            name='stage_slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='tripstage',
            name='stage_slug_fr',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='tripstage',
            name='story_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripstage',
            name='story_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='type_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='type_fr',
            field=models.CharField(max_length=25, null=True, verbose_name='Type'),
        ),
    ]
