# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0046_auto_20160610_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripstage',
            name='trips',
        ),
        migrations.AddField(
            model_name='tripstage',
            name='trip_linked',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='map.Trip', verbose_name='Aventure liée'),
            preserve_default=False,
        ),
    ]
